feature!: Unified pylace
promised-ai/lace pull request #31
Opened 2023-03-02 03:35 UTC by schmidmt

This PR unified the `pylace` python package into one module instead of two. There are also some documentation and name changes.

2023-03-02 22:01 UTC, Swandog requested changes
Looks mostly good. Had a few questions. Biggest issue is Python 3.7.

Appreciate tracking down the straggling Braid references!

2023-03-02 22:01 UTC, Swandog commented on CONTRIBUTING.md
> +# Contributing to Lace
Good catches!

2023-03-02 22:01 UTC, Swandog commented on book/book.toml
> +git-repository-url = "https://github.com/promised-ai/lace"
👍

2023-03-02 22:01 UTC, Swandog commented on lace/Dockerfile
> +COPY --from=base /rp/target/release/lace /bin/lace
Really good work 👍

2023-03-02 22:01 UTC, Swandog commented on lace/bin/opt.rs
> +    #[clap(name = "LACEFILE_OUT")]
I just want to be clear how much I appreciate you catching these 👍

2023-03-02 22:01 UTC, Swandog commented on lace/lace_cc/src/assignment.rs
> +/// Validates assignments if the `LACE_NOCHECK` is not set to `"1"`.
So I'm going to comment on every single one, to demonstrate my appreciation 👍

2023-03-02 22:01 UTC, Swandog commented on pylace/pyproject.toml
> -line-length = 80
Any reason you decided to remove the `black` configuration?

Otherwise I will assume that moving the `pyproject` stuff here makes sense

2023-03-02 22:01 UTC, Swandog commented on lace/README.md
> -# Lace
Why did you delete the Rust-specific README?

2023-03-02 22:01 UTC, Swandog commented on pylace/pyproject.toml
> +requires-python = ">=3.7"
I tried doing `pip install .` in `lace` on a `python:3.7-bullseye` Docker container, and I got this error:
```
ERROR: Could not find a version that satisfies the requirement numpy~=1.24.2 (from pylace) (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6)
ERROR: No matching distribution found for numpy~=1.24.2
```

I think maybe we need to be 3.8 or higher?

(I tried compiling it in python 3.10 and Docker started hanging, but I think that's not related)

2023-03-06 16:20 UTC, schmidmt commented on lace/bin/opt.rs
> +    #[clap(name = "LACEFILE_OUT")]
Of course!

2023-03-06 16:21 UTC, schmidmt commented on pylace/pyproject.toml
> -line-length = 80
I applied mv too liberally... Will fix.

2023-03-06 17:09 UTC, schmidmt commented on lace/README.md
> -# Lace
I put it back.

2023-03-07 00:38 UTC, schmidmt commented on pylace/pyproject.toml
> +requires-python = ">=3.7"
The latest code should address this.

2023-03-10 01:30 UTC, Swandog approved these changes
I have some thoughts. But I think that if we want to change them, it would be better to get this out, and then circle back to fix them, rather than hold this PR further.

(Note: I would like you to check that my changes make sense too; they're pretty small)

Approved

2023-03-10 01:30 UTC, Swandog commented on .github/workflows/rust-build-test.yaml
> +  features:
Can we re-name this, to something like `check-all-features`?

2023-03-10 01:30 UTC, Swandog commented on .github/workflows/rust-build-test.yaml
> +      - name: Run cargo hack
Can we rename this? The real thing we're running here is `check`, not `hack`

2023-03-10 01:30 UTC, Swandog commented on .github/workflows/rust-build-test.yaml
> +          RUSTFLAGS: -C debuginfo=0
Is there any reason to use this rather than `--release`?

2023-03-10 01:30 UTC, Swandog commented on .github/workflows/rust-build-test.yaml
> +    if: startsWith(github.ref, 'refs/tags/rust')
Will this ever happen? If I'm reading https://docs.github.com/en/actions/learn-github-actions/contexts#github-context correctly, this will only ever be `refs/tags/` if someone pushes a tag, but this isn't set up to run on tags

2023-03-10 01:30 UTC, Swandog commented on .github/workflows/rust-build-test.yaml
> +      - '.github/workflows/rust-build-test.yaml'
Do we really want to run this on pushes to `master`/`main`? We shouldn't really be allowing those anyway; everything should have to go through Pull Requests

2023-03-10 01:30 UTC, Swandog commented on .github/workflows/rust-build-test.yaml
> +
This new workflow is not compiling the benchmarks, like the old one did

2023-03-10 01:30 UTC, Swandog commented on .github/workflows/python-build-test.yaml
> +      - master
Same comment as in the Rust one

2023-03-10 01:30 UTC, Swandog commented on .github/workflows/python-build-test.yaml
> +          ruff . --exit-non-zero-on-fix
Why are we using `ruff`? Isn't it better to only have one formatter?

2023-03-10 01:30 UTC, Swandog commented on .github/workflows/python-build-test.yaml
> +          toolchain: nightly-2023-02-14
I think it's probably bad to lock the toolchain to a specific nightly unless there's a compelling reason to

2023-03-10 01:30 UTC, Swandog commented on pylace/lace/analysis.py
> +    from lace import Engine
why do we only import `Engine` if we are doing `TYPE_CHECKING`?

2023-03-10 01:30 UTC, Swandog commented on pylace/lace/analysis.py
> +    engine: "Engine",
Is this really correct? I thought classes should be bare words

2023-03-10 01:30 UTC, Swandog commented on pylace/lace/engine.py
> +if TYPE_CHECKING:
Similar questions as in `analysis.py`

2023-03-10 01:30 UTC, Swandog commented on pylace/lace/engine.py
> +        >>> engine = Satellites()  # doctest: +SKIP
Personally I disagree with this, which I gather comes from `blackdoc`? But I'm not gonna bikeshed over it.

2023-03-10 01:30 UTC, Swandog commented on pylace/src/utils.rs
> +        //     "Simulated unsupported ftype: {ftype:?}"
If this isn't useful it should be deleted

2023-03-10 01:30 UTC, Swandog commented on pylace/src/utils.rs
> +            // ))),
More commented out code

2023-03-10 01:30 UTC, Swandog commented on pylace/tests/dummy_test.py
> +    pass
This probably isn't necessary anymore since `example_test.py` (with `test_animals`) exists, right?

2023-03-10 01:30 UTC, Swandog commented on pylace/tests/dummy_test.py
> +    Tests the tes only exists to ensure that there is at least 1 test for `pytest`,
If this is going to stay, "tes" is a typo

2023-03-10 01:31 UTC, Swandog commented
Also note: I figured I would bump the Polars version after this came out. I'd really rather just do that separately.

2023-03-10 16:17 UTC, merged